version: '3.8'
services:

  api: 
    build: .
    ports:
      - '3000:3000'

  api2: 
    build: .
    ports:
      - '3001:3000'

  load_balancer:
    image: nginx:latest
    ports:
      - '8080:80'
    depends_on:
      - api
      - api2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
